const G = 9.81, R = Math.PI/180;
const SEG = {braco:0.186, antebraco:0.146, mao:0.055, coxa:0.245, perna:0.246, pe:0.152, tronco:0.288};
/* gabaritos genéricos de curva de força por articulação (literatura, forma e não medida):
   pc = onde a capacidade é máxima, em fração da amplitude (0 = alongado, 1 = encurtado) */
const CAPACIDADE = {
  "Cotovelo":{pc:0.50,sd:0.32,base:0.34}, "Ombro":{pc:0.34,sd:0.34,base:0.34},
  "Joelho":{pc:0.40,sd:0.32,base:0.34},   "Quadril":{pc:0.20,sd:0.38,base:0.36},
  "Lombar":{pc:0.24,sd:0.38,base:0.36},   "Quadril/lombar":{pc:0.24,sd:0.38,base:0.36},
  "Tronco":{pc:0.26,sd:0.38,base:0.36},   "Tornozelo":{pc:0.26,sd:0.36,base:0.42},
  "Punho":{pc:0.46,sd:0.32,base:0.40},    "Escápula":{pc:0.50,sd:0.45,base:0.55}
};
function capacidadeEm(junta, p){
  const c = CAPACIDADE[junta] || {pc:0.42,sd:0.35,base:0.36};
  const sino = Math.exp(-((p-c.pc)**2)/(2*c.sd*c.sd));
  return c.base + (1-c.base)*sino;
}
/* exigência = quanto a carga pede naquele ponto dividido pelo que o músculo consegue ali */
function aderencia(r){
  const ex = r.pontos.map(pt => {
    const rel = r.pico>0 ? pt.tau/r.pico : 0;
    return {p:pt.p, cap:capacidadeEm(r.jt.j, pt.p), exig: rel/capacidadeEm(r.jt.j, pt.p)};
  });
  let maxE=0, iMax=0;
  ex.forEach((o,i)=>{ if(o.exig>maxE){maxE=o.exig; iMax=i;} });
  const media = ex.reduce((a,o)=>a+o.exig,0)/ex.length;
  return {serie:ex, pAderencia:ex[iMax].p, casamento: maxE>0 ? media/maxE*100 : 0};
}
const JOINT_MAXROM = {"Ombro":180,"Cotovelo":145,"Joelho":130,"Quadril":120,"Quadril/lombar":100,"Lombar":90,"Tornozelo":35,"Tronco":90,"Punho":70,"Escápula":45};
const maxRom = j => JOINT_MAXROM[j] || 90;

/* ---------- BIBLIOTECA ---------- */
/* b0 = ângulo do segmento na posição ALONGADA (0° = horizontal à frente, -90° = apontando para baixo)
   db = giro total até o fim da fase de subida
   gamma = direção da força aplicada (-90 = gravidade, +90 = polia acima, 180 = polia à frente)
   off = braço de momento extra constante, em metros                                            */
const BASE = [
 // PEITO
 {id:"supino-reto",nome:"Supino reto com barra",grupo:"Peito",carga:80,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.05,b0:0,db:-70,g:-90,off:0}],
  nota:"Pico com o peitoral alongado, perto do peito; no travamento o torque some."},
 {id:"supino-inclinado",nome:"Supino inclinado 30°",grupo:"Peito",carga:70,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.05,b0:5,db:-78,g:-90,off:0}],
  nota:"Amplitude de ombro maior, então mais área embaixo da curva por quilo."},
 {id:"crucifixo",nome:"Crucifixo com halteres",grupo:"Peito",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.55,b0:0,db:-80,g:-90,off:0}],
  nota:"Braço longo e carga pequena: torque alto no alongado, quase nada no topo."},
 {id:"crossover",nome:"Crossover na polia",grupo:"Peito",carga:18,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:180,db:-90,g:180,off:0}],
  nota:"Cabo horizontal: o pico migra para o fim da adução, com o peitoral encurtado."},
 {id:"peck-deck",nome:"Peck deck",grupo:"Peito",carga:45,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:0.7,b0:175,db:-85,g:180,off:0.16}],
  nota:"A came da máquina achata a curva: menos pico, tensão mais constante."},

 // COSTAS
 {id:"barra-fixa",nome:"Barra fixa pronada",grupo:"Costas",carga:0,tipo:"corporal",frac:1,bi:false,
  juntas:[{j:"Ombro",seg:"fixo",f:0.05,b0:-90,db:55,g:-90,off:0.03}],
  nota:"O corpo fica embaixo da barra: a linha de força passa rente ao ombro."},
 {id:"puxada-frontal",nome:"Puxada frontal na polia",grupo:"Costas",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"fixo",f:0.03,b0:-90,db:55,g:-90,off:0.22}],
  nota:"Sentado, a barra fica à frente do ombro: mesmo peso, braço de momento muito maior."},
 {id:"remada-curvada",nome:"Remada curvada",grupo:"Costas",carga:60,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.2,b0:-90,db:50,g:-90,off:0},
          {j:"Quadril/lombar",seg:"tronco",f:0.5,b0:-15,db:-10,g:-90,off:0.05}],
  nota:"Duas contas ao mesmo tempo: o dorsal puxa e a lombar segura o tronco parado."},
 {id:"remada-sentada",nome:"Remada sentada na polia",grupo:"Costas",carga:65,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.1,b0:-10,db:-70,g:180,off:0}],
  nota:"Força horizontal: quase nada de carga na lombar, tudo na extensão do ombro."},
 {id:"pullover",nome:"Pullover na polia, braços retos",grupo:"Costas",carga:30,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.6,b0:60,db:-150,g:-90,off:0}],
  nota:"Braço longo e pico no meio da amplitude."},

 // BÍCEPS
 {id:"rosca-direta",nome:"Rosca direta com halteres",grupo:"Bíceps",carga:15,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-90,db:145,g:-90,off:0}],
  nota:"Pico exatamente a 90° de flexão; embaixo e em cima o torque cai a zero."},
 {id:"rosca-scott",nome:"Rosca Scott",grupo:"Bíceps",carga:14,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-45,db:105,g:-90,off:0}],
  nota:"O banco inclinado adianta o pico: ele chega na primeira metade da subida, bem antes do da rosca direta."},
 {id:"rosca-inclinada",nome:"Rosca inclinada no banco 45°",grupo:"Bíceps",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-100,db:150,g:-90,off:0}],
  nota:"Ombro estendido: o bíceps trabalha mais alongado do que a conta do cotovelo mostra."},
 {id:"rosca-martelo",nome:"Rosca martelo",grupo:"Bíceps",carga:16,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.2,b0:-90,db:140,g:-90,off:0}],
  nota:"Pegada neutra, braço um pouco maior até o centro da mão."},
 {id:"rosca-polia-baixa",nome:"Rosca na polia baixa",grupo:"Bíceps",carga:15,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-90,db:145,g:-70,off:0}],
  nota:"O cabo inclinado desloca o pico e mantém tensão no começo."},

 // TRÍCEPS
 {id:"triceps-polia",nome:"Tríceps na polia alta",grupo:"Tríceps",carga:25,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:0,db:-85,g:90,off:0}],
  nota:"No travamento o braço de momento vai a zero: o fim da repetição é quase de graça."},
 {id:"triceps-testa",nome:"Tríceps testa deitado",grupo:"Tríceps",carga:25,tipo:"externa",bi:true,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:160,db:-70,g:-90,off:0}],
  nota:"Pico com o cotovelo bem flexionado, tríceps alongado."},
 {id:"triceps-frances",nome:"Tríceps francês acima da cabeça",grupo:"Tríceps",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:170,db:-80,g:-90,off:0}],
  nota:"Ombro flexionado alonga a porção longa do tríceps no ponto de maior torque."},
 {id:"paralelas",nome:"Mergulho nas paralelas",grupo:"Tríceps",carga:0,tipo:"corporal",frac:0.65,bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.0,b0:-30,db:-60,g:-90,off:0}],
  nota:"Peso corporal inteiro sobre um braço de momento que cresce no fundo."},
 {id:"triceps-coice",nome:"Tríceps coice",grupo:"Tríceps",carga:8,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:-90,db:-90,g:-90,off:0}],
  nota:"Só fica pesado no travamento, com o tríceps encurtado — o contrário do testa."},

 // OMBRO
 {id:"press-militar",nome:"Desenvolvimento militar em pé",grupo:"Ombro",carga:40,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:-10,db:-75,g:-90,off:0}],
  nota:"Barra livre passa rente ao ombro na subida."},
 {id:"press-smith",nome:"Desenvolvimento no Smith",grupo:"Ombro",carga:40,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:-10,db:-75,g:-90,off:0.06}],
  nota:"A barra guiada obriga um trajeto à frente do ombro: braço de momento extra o tempo todo."},
 {id:"elevacao-lateral",nome:"Elevação lateral com halteres",grupo:"Ombro",carga:10,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:-90,db:90,g:-90,off:0}],
  nota:"Zero de torque embaixo, máximo a 90°: é um exercício de metade de cima."},
 {id:"elevacao-lateral-polia",nome:"Elevação lateral na polia baixa",grupo:"Ombro",carga:9,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:-90,db:90,g:-20,off:0}],
  nota:"O cabo diagonal carrega justamente o começo, onde o halter não carrega nada."},
 {id:"crucifixo-inverso",nome:"Crucifixo inverso",grupo:"Ombro",carga:10,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:90,db:90,g:-90,off:0}],
  nota:"Pico no fim da abdução horizontal."},

 // QUADRÍCEPS
 {id:"agachamento-livre",nome:"Agachamento livre",grupo:"Quadríceps",carga:100,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.55,b0:-35,db:-55,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.55,b0:-30,db:-60,g:-90,off:0}],
  nota:"Duas articulações dividem o serviço; a profundidade é quem define quanto cada uma pega."},
 {id:"agachamento-frontal",nome:"Agachamento frontal",grupo:"Quadríceps",carga:80,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.62,b0:-32,db:-58,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.35,b0:-30,db:-60,g:-90,off:0}],
  nota:"Tronco mais vertical: o joelho assume, o quadril alivia."},
 {id:"hack",nome:"Hack machine",grupo:"Quadríceps",carga:140,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.70,b0:-30,db:-60,g:-90,off:0}],
  nota:"Encosto estabiliza e permite carga alta com quase todo o torque no joelho."},
 {id:"leg-press",nome:"Leg press 45°",grupo:"Quadríceps",carga:200,tipo:"externa",bi:false,ff:0.707,
  juntas:[{j:"Joelho",seg:"perna",f:0.6,b0:-140,db:50,g:-45,off:0}],
  nota:"A força vem no eixo do trilho, não na vertical — por isso a carga escrita engana."},
 {id:"extensora",nome:"Cadeira extensora",grupo:"Quadríceps",carga:40,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.85,b0:-90,db:90,g:-90,off:0}],
  nota:"Pico no encurtado, torque nulo no começo: curva espelhada à do agachamento."},
 {id:"bulgaro",nome:"Agachamento búlgaro",grupo:"Quadríceps",carga:24,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.5,b0:-38,db:-52,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.6,b0:-25,db:-55,g:-90,off:0}],
  nota:"Uma perna só: pouca carga na barra, muito torque por articulação."},

 // POSTERIOR E GLÚTEO
 {id:"stiff",nome:"Stiff com barra",grupo:"Posterior e glúteo",carga:80,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.85,b0:-10,db:-80,g:-90,off:0},
          {j:"Lombar",seg:"tronco",f:0.45,b0:-10,db:-80,g:-90,off:0}],
  nota:"Torque máximo com o isquiotibial no maior comprimento."},
 {id:"terra",nome:"Levantamento terra",grupo:"Posterior e glúteo",carga:140,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.7,b0:-25,db:-65,g:-90,off:0},
          {j:"Joelho",seg:"perna",f:0.3,b0:-40,db:-50,g:-90,off:0}],
  nota:"Carga altíssima, mas o braço de momento despenca conforme o tronco sobe."},
 {id:"hip-thrust",nome:"Elevação pélvica",grupo:"Posterior e glúteo",carga:120,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.55,b0:-60,db:60,g:-90,off:0}],
  nota:"Único da lista com pico no topo, glúteo totalmente encurtado."},
 {id:"mesa-flexora",nome:"Mesa flexora",grupo:"Posterior e glúteo",carga:35,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.85,b0:0,db:-90,g:-90,off:0}],
  nota:"Pico logo na saída, com a perna estendida."},
 {id:"flexora-sentada",nome:"Cadeira flexora sentada",grupo:"Posterior e glúteo",carga:35,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.85,b0:-10,db:-80,g:-90,off:0}],
  nota:"Quadril flexionado deixa o isquiotibial mais alongado durante toda a série."},
 {id:"coice-polia",nome:"Coice de glúteo na polia",grupo:"Posterior e glúteo",carga:15,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"coxa",f:1.0,b0:-40,db:50,g:-90,off:0}],
  nota:"Braço de momento grande com carga pequena."},

 // PANTURRILHA
 {id:"panturrilha-pe",nome:"Panturrilha em pé",grupo:"Panturrilha",carga:100,tipo:"externa",bi:false,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-10,db:30,g:-90,off:0.14}],
  nota:"Braço de momento quase constante: curva achatada, trabalho por repetição baixo."},
 {id:"panturrilha-sentada",nome:"Panturrilha sentada",grupo:"Panturrilha",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-10,db:30,g:-90,off:0.14}],
  nota:"Joelho dobrado tira o gastrocnêmio e sobra o sóleo."}
 ,
 // ---- ACRÉSCIMOS ----
 {id:"supino-halteres",nome:"Supino com halteres",grupo:"Peito",carga:30,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.15,b0:8,db:-80,g:-90,off:0}],
  nota:"Amplitude maior que a barra: mais graus girados, mais área de trabalho."},
 {id:"flexao-braco",nome:"Flexão de braço no solo",grupo:"Peito",carga:0,tipo:"corporal",frac:0.65,bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:0,db:-65,g:-90,off:0}],
  nota:"Só cerca de dois terços do peso do corpo chega aos braços."},
 {id:"supino-maquina",nome:"Supino na máquina",grupo:"Peito",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:0.75,b0:-90,db:70,g:180,off:0.12}],
  nota:"Trajeto guiado e braço de momento mais parelho do começo ao fim."},

 {id:"chin-up",nome:"Barra fixa supinada",grupo:"Costas",carga:0,tipo:"corporal",frac:1,bi:false,
  juntas:[{j:"Ombro",seg:"fixo",f:0.045,b0:-90,db:60,g:-90,off:0.028}],
  nota:"Pegada supinada aproxima o corpo da barra e muda pouco o braço de momento."},
 {id:"remada-unilateral",nome:"Remada unilateral com halter",grupo:"Costas",carga:32,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.3,b0:-90,db:55,g:-90,off:0}],
  nota:"Tronco apoiado tira a lombar da conta e sobra tudo para o dorsal."},
 {id:"remada-cavalinho",nome:"Remada cavalinho",grupo:"Costas",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.2,b0:-90,db:50,g:-90,off:0},
          {j:"Quadril/lombar",seg:"tronco",f:0.45,b0:-20,db:-10,g:-90,off:0.05}],
  nota:"Apoio no peito reduz, mas não zera, o torque da lombar."},
 {id:"puxada-neutra",nome:"Puxada com pegada neutra",grupo:"Costas",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"fixo",f:0.03,b0:-90,db:55,g:-90,off:0.17}],
  nota:"Puxar mais perto do corpo corta 5 cm do braço de momento da puxada aberta."},
 {id:"face-pull",nome:"Face pull na polia",grupo:"Costas",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.2,b0:10,db:-70,g:180,off:0}],
  nota:"Cabo horizontal na altura do rosto: pico na abdução horizontal final."},

 {id:"rosca-barra-w",nome:"Rosca com barra W",grupo:"Bíceps",carga:25,tipo:"externa",bi:true,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-90,db:140,g:-90,off:0}],
  nota:"Barra bilateral: cada cotovelo pega metade, se você marcar a divisão lá em cima."},
 {id:"rosca-spider",nome:"Rosca spider no banco inclinado",grupo:"Bíceps",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-90,db:100,g:-90,off:0}],
  nota:"Braço na vertical: torque zero na largada e pico perto do fecho."},
 {id:"rosca-inversa",nome:"Rosca inversa",grupo:"Bíceps",carga:12,tipo:"externa",bi:true,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-90,db:135,g:-90,off:0}],
  nota:"Mesma alavanca da direta, com braquiorradial assumindo mais serviço."},

 {id:"supino-fechado",nome:"Supino com pegada fechada",grupo:"Tríceps",carga:60,tipo:"externa",bi:true,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.0,b0:-30,db:-60,g:-90,off:0}],
  nota:"O tríceps recebe cargas que nenhum isolado suporta."},
 {id:"triceps-corda-alta",nome:"Tríceps corda acima da cabeça",grupo:"Tríceps",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:170,db:-80,g:-45,off:0}],
  nota:"Cabo diagonal deixa a curva mais constante do que o halter."},
 {id:"triceps-coice-polia",nome:"Tríceps coice na polia",grupo:"Tríceps",carga:10,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:-90,db:-90,g:180,off:0}],
  nota:"Mesmo gesto do coice com halter e curva invertida: aqui o pico é no alongado."},

 {id:"desenvolvimento-halteres",nome:"Desenvolvimento com halteres",grupo:"Ombro",carga:24,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:-5,db:-80,g:-90,off:0}],
  nota:"Halteres soltos permitem descer mais e girar mais graus."},
 {id:"arnold",nome:"Desenvolvimento Arnold",grupo:"Ombro",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:5,db:-95,g:-90,off:0}],
  nota:"A maior amplitude da lista para ombro."},
 {id:"elevacao-frontal",nome:"Elevação frontal",grupo:"Ombro",carga:8,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:-90,db:90,g:-90,off:0}],
  nota:"Gêmea da lateral no plano da frente, mesma curva."},
 {id:"remada-alta",nome:"Remada alta",grupo:"Ombro",carga:30,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:-90,db:70,g:-90,off:0}],
  nota:"Carga maior que a elevação porque o braço de momento é bem menor."},

 {id:"afundo",nome:"Afundo com halteres",grupo:"Quadríceps",carga:30,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.55,b0:-35,db:-55,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.45,b0:-25,db:-55,g:-90,off:0}],
  nota:"Unilateral: pouca carga na mão, torque por perna comparável ao agachamento."},
 {id:"agachamento-smith",nome:"Agachamento no Smith",grupo:"Quadríceps",carga:90,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.68,b0:-30,db:-60,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.3,b0:-28,db:-58,g:-90,off:0}],
  nota:"Pés à frente e barra guiada: o joelho recebe o que o quadril deixou de receber."},
 {id:"sissy-squat",nome:"Sissy squat",grupo:"Quadríceps",carga:0,tipo:"corporal",frac:0.55,bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.95,b0:-20,db:-70,g:-90,off:0}],
  nota:"Braço de momento enorme no joelho com zero de carga externa."},
 {id:"leg-press-horizontal",nome:"Leg press horizontal",grupo:"Quadríceps",carga:150,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.55,b0:-95,db:55,g:180,off:0}],
  nota:"Força horizontal: a conta muda porque a direção da resistência mudou."},

 {id:"bom-dia",nome:"Bom dia com barra",grupo:"Posterior e glúteo",carga:50,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.8,b0:-10,db:-80,g:-90,off:0},
          {j:"Lombar",seg:"tronco",f:0.5,b0:-10,db:-80,g:-90,off:0}],
  nota:"A barra nas costas fica longe do quadril: torque alto com carga baixa."},
 {id:"terra-romeno-halteres",nome:"Terra romeno com halteres",grupo:"Posterior e glúteo",carga:50,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.8,b0:-12,db:-78,g:-90,off:0}],
  nota:"Halteres descem mais rente às pernas e encurtam um pouco o braço de momento."},
 {id:"terra-sumo",nome:"Levantamento terra sumô",grupo:"Posterior e glúteo",carga:140,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.55,b0:-35,db:-55,g:-90,off:0},
          {j:"Joelho",seg:"perna",f:0.4,b0:-40,db:-50,g:-90,off:0}],
  nota:"Tronco mais vertical que o convencional: menos quadril, mais joelho."},
 {id:"extensao-lombar-45",nome:"Extensão lombar no banco 45°",grupo:"Posterior e glúteo",carga:0,tipo:"corporal",frac:0.6,bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.75,b0:-60,db:60,g:-90,off:0}],
  nota:"Diferente do stiff: aqui o pico chega no topo, com o glúteo encurtado."},
 {id:"abducao-maquina",nome:"Abdução de quadril na máquina",grupo:"Posterior e glúteo",carga:50,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"coxa",f:0.9,b0:-95,db:40,g:-90,off:0}],
  nota:"Pico no fim da abertura, glúteo médio encurtado."},

 {id:"panturrilha-leg-press",nome:"Panturrilha no leg press",grupo:"Panturrilha",carga:180,tipo:"externa",bi:false,ff:0.707,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-10,db:30,g:-45,off:0.14}],
  nota:"A carga escrita é grande, mas só a componente no eixo do trilho chega ao pé."},

 {id:"abdominal-polia",nome:"Abdominal na polia ajoelhado",grupo:"Abdômen",carga:40,tipo:"externa",bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.45,b0:90,db:-50,g:90,off:0}],
  nota:"Quanto mais o tronco flexiona, maior o braço de momento: pico no encurtado."},
 {id:"elevacao-pernas",nome:"Elevação de pernas suspenso",grupo:"Abdômen",carga:0,tipo:"corporal",frac:0.32,bi:false,
  juntas:[{j:"Quadril",seg:"coxa",f:1.7,b0:-90,db:90,g:-90,off:0}],
  nota:"Perna esticada dobra o braço de momento em relação à perna dobrada."},
 {id:"abdominal-maquina",nome:"Abdominal na máquina",grupo:"Abdômen",carga:45,tipo:"externa",bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.5,b0:80,db:-50,g:-90,off:0}],
  nota:"Encosto fixa a pelve e concentra o torque na flexão do tronco."},

 {id:"rosca-punho",nome:"Rosca de punho",grupo:"Antebraço",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Punho",seg:"fixo",f:0.045,b0:-30,db:70,g:-90,off:0}],
  nota:"Alavanca curtíssima: muita carga para pouquíssimo torque."},
 {id:"encolhimento",nome:"Encolhimento com halteres",grupo:"Trapézio",carga:70,tipo:"externa",bi:false,
  juntas:[{j:"Escápula",seg:"fixo",f:0.02,b0:-45,db:40,g:-90,off:0.05}],
  nota:"Movimento quase de translação: o modelo de alavanca aqui é só uma aproximação grosseira."},

 // ---- SEGUNDA LEVA ----
 // PEITO
 {id:"supino-declinado",nome:"Supino declinado",grupo:"Peito",carga:80,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.05,b0:-8,db:-62,g:-90,off:0}],
  nota:"Menos amplitude de ombro que o reto: menos graus girados, menos área de trabalho."},
 {id:"crucifixo-inclinado",nome:"Crucifixo inclinado",grupo:"Peito",carga:16,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.55,b0:8,db:-78,g:-90,off:0}],
  nota:"Mesma alavanca longa do crucifixo reto, com o peitoral superior mais alongado embaixo."},
 {id:"crossover-alto",nome:"Crossover na polia alta",grupo:"Peito",carga:16,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:120,db:-110,g:120,off:0}],
  nota:"O cabo vem de cima e da frente: o pico só aparece quando as mãos cruzam embaixo."},
 {id:"flexao-pes-elevados",nome:"Flexão com pés elevados",grupo:"Peito",carga:0,tipo:"corporal",frac:0.75,bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.0,b0:5,db:-70,g:-90,off:0}],
  nota:"Elevar os pés joga mais peso do corpo para os braços do que a flexão no chão."},

 // COSTAS
 {id:"remada-invertida",nome:"Remada invertida na barra",grupo:"Costas",carga:0,tipo:"corporal",frac:0.65,bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.2,b0:-90,db:58,g:-90,off:0}],
  nota:"Corpo na horizontal: o braço de momento cresce conforme o peito sobe."},
 {id:"pullover-halter",nome:"Pullover com halter",grupo:"Costas",carga:25,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:170,db:-80,g:-90,off:0}],
  nota:"Torque máximo com os braços atrás da cabeça e zero no topo: o oposto de toda puxada."},
 {id:"puxada-nuca",nome:"Puxada atrás da nuca",grupo:"Costas",carga:55,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"fixo",f:0.03,b0:-90,db:46,g:-90,off:0.26}],
  nota:"Braço de momento ainda maior que o da frontal, com menos graus de amplitude."},
 {id:"remada-maquina",nome:"Remada na máquina",grupo:"Costas",carga:70,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.1,b0:-5,db:-65,g:180,off:0.03}],
  nota:"Peito apoiado e trajeto guiado: quase nada sobra para a lombar."},
 {id:"remada-yates",nome:"Remada curvada supinada",grupo:"Costas",carga:65,tipo:"externa",bi:true,
  juntas:[{j:"Ombro",seg:"braco",f:1.15,b0:-90,db:45,g:-90,off:0},
          {j:"Quadril/lombar",seg:"tronco",f:0.4,b0:-30,db:-8,g:-90,off:0.05}],
  nota:"Tronco mais ereto que a curvada pronada: o torque lombar cai quase pela metade."},

 // BÍCEPS
 {id:"rosca-concentrada",nome:"Rosca concentrada",grupo:"Bíceps",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-80,db:120,g:-90,off:0}],
  nota:"Cotovelo travado na coxa: mesma curva da direta, sem ajuda de balanço."},
 {id:"rosca-polia-alta",nome:"Rosca na polia alta",grupo:"Bíceps",carga:10,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:170,db:-80,g:180,off:0}],
  nota:"Braço aberto na altura do ombro: o pico cai no meio da flexão."},
 {id:"rosca-bayesiana",nome:"Rosca na polia atrás do corpo",grupo:"Bíceps",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.15,b0:-100,db:140,g:-150,off:0}],
  nota:"Cabo puxando de trás: o único da lista que chega ao pico com o bíceps ainda alongado."},
 {id:"rosca-martelo-corda",nome:"Rosca martelo na polia com corda",grupo:"Bíceps",carga:18,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.2,b0:-90,db:140,g:-75,off:0}],
  nota:"O cabo levemente inclinado mantém tensão onde o halter já zerou."},

 // TRÍCEPS
 {id:"mergulho-banco",nome:"Mergulho no banco",grupo:"Tríceps",carga:0,tipo:"corporal",frac:0.55,bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.0,b0:-25,db:-55,g:-90,off:0}],
  nota:"Pés no chão tiram parte do peso: menos carga que nas paralelas."},
 {id:"triceps-maquina",nome:"Extensão de tríceps na máquina",grupo:"Tríceps",carga:35,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:0.9,b0:20,db:-75,g:90,off:0.04}],
  nota:"A came segura tensão no travamento, onde a polia livre entrega de graça."},
 {id:"triceps-unilateral-polia",nome:"Tríceps unilateral na polia",grupo:"Tríceps",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Cotovelo",seg:"antebraco",f:1.1,b0:5,db:-80,g:90,off:0}],
  nota:"Mesma curva da polia bilateral, com carga por braço bem menor."},

 // OMBRO
 {id:"elevacao-lateral-maquina",nome:"Elevação lateral na máquina",grupo:"Ombro",carga:25,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:0.75,b0:-85,db:80,g:-90,off:0.05}],
  nota:"O apoio no braço encurta a alavanca e permite mais carga pelo mesmo torque."},
 {id:"elevacao-lateral-inclinada",nome:"Elevação lateral inclinada",grupo:"Ombro",carga:8,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:-70,db:95,g:-90,off:0}],
  nota:"Inclinar o corpo desloca o pico para mais cedo na subida."},
 {id:"desenvolvimento-maquina",nome:"Desenvolvimento na máquina",grupo:"Ombro",carga:45,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:0.8,b0:-15,db:-70,g:-90,off:0.05}],
  nota:"Trajeto guiado com um braço de momento residual do começo ao fim."},
 {id:"crucifixo-inverso-polia",nome:"Crucifixo inverso na polia",grupo:"Ombro",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Ombro",seg:"braco",f:1.5,b0:170,db:-85,g:180,off:0}],
  nota:"O cabo horizontal carrega o começo da abertura, onde o halter não carrega nada."},

 // QUADRÍCEPS
 {id:"goblet",nome:"Agachamento goblet",grupo:"Quadríceps",carga:30,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.55,b0:-35,db:-55,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.4,b0:-25,db:-55,g:-90,off:0}],
  nota:"Peso na frente do peito mantém o tronco ereto e alivia o quadril."},
 {id:"step-up",nome:"Subida no banco",grupo:"Quadríceps",carga:24,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.5,b0:-40,db:-50,g:-90,off:0},
          {j:"Quadril",seg:"tronco",f:0.45,b0:-30,db:-50,g:-90,off:0}],
  nota:"Uma perna de cada vez: carga baixa na mão, torque alto por articulação."},
 {id:"extensora-unilateral",nome:"Cadeira extensora unilateral",grupo:"Quadríceps",carga:22,tipo:"externa",bi:false,
  juntas:[{j:"Joelho",seg:"perna",f:0.85,b0:-90,db:90,g:-90,off:0}],
  nota:"Mesma curva da bilateral com metade da carga — e o dobro de atenção por perna."},
 {id:"leg-press-unilateral",nome:"Leg press unilateral",grupo:"Quadríceps",carga:100,tipo:"externa",bi:false,ff:0.707,
  juntas:[{j:"Joelho",seg:"perna",f:0.6,b0:-140,db:50,g:-45,off:0}],
  nota:"Metade da carga do bilateral produz o mesmo torque em um joelho só."},

 // POSTERIOR E GLÚTEO
 {id:"nordico",nome:"Flexor nórdico",grupo:"Posterior e glúteo",carga:0,tipo:"corporal",frac:0.85,bi:false,
  juntas:[{j:"Joelho",seg:"tronco",f:1.15,b0:90,db:-80,g:-90,off:0}],
  nota:"Sem nenhuma carga externa, o torque de pico rivaliza com o da mesa flexora carregada."},
 {id:"hip-thrust-unilateral",nome:"Elevação pélvica unilateral",grupo:"Posterior e glúteo",carga:50,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.55,b0:-60,db:60,g:-90,off:0}],
  nota:"Mesma curva com pico no topo, concentrada em um quadril."},
 {id:"stiff-unilateral",nome:"Stiff unilateral",grupo:"Posterior e glúteo",carga:30,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"tronco",f:0.85,b0:-10,db:-75,g:-90,off:0}],
  nota:"Carga pequena na mão e torque de quadril comparável ao stiff com barra."},
 {id:"abducao-polia",nome:"Abdução de quadril na polia",grupo:"Posterior e glúteo",carga:12,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"coxa",f:1.0,b0:-95,db:40,g:-90,off:0}],
  nota:"Geometria quase igual à da máquina, com carga menor: serve para medir o que a anilha muda."},
 {id:"coice-maquina",nome:"Coice de glúteo na máquina",grupo:"Posterior e glúteo",carga:35,tipo:"externa",bi:false,
  juntas:[{j:"Quadril",seg:"coxa",f:0.8,b0:-40,db:50,g:-90,off:0.04}],
  nota:"O apoio na coxa encurta a alavanca e deixa carregar bem mais que na polia."},

 // PANTURRILHA
 {id:"panturrilha-smith",nome:"Panturrilha no Smith",grupo:"Panturrilha",carga:110,tipo:"externa",bi:false,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-10,db:30,g:-90,off:0.14}],
  nota:"Barra guiada nas costas: mesma alavanca curta da panturrilha em pé."},
 {id:"panturrilha-unilateral",nome:"Panturrilha unilateral",grupo:"Panturrilha",carga:0,tipo:"corporal",frac:1,bi:false,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-12,db:32,g:-90,off:0.14}],
  nota:"O peso do corpo inteiro sobre um tornozelo só, sem precisar de anilha."},
 {id:"panturrilha-burrinho",nome:"Panturrilha burrinho",grupo:"Panturrilha",carga:120,tipo:"externa",bi:false,
  juntas:[{j:"Tornozelo",seg:"pe",f:0.1,b0:-10,db:32,g:-90,off:0.15}],
  nota:"Tronco dobrado muda pouco a conta do tornozelo e muito o alongamento do gastrocnêmio."},

 // ABDÔMEN
 {id:"abdominal-solo",nome:"Abdominal no solo",grupo:"Abdômen",carga:0,tipo:"corporal",frac:0.3,bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.45,b0:0,db:-40,g:-90,off:0}],
  nota:"Pico logo na saída do chão, com o abdômen alongado — o oposto da polia."},
 {id:"prancha",nome:"Prancha abdominal",grupo:"Abdômen",carga:0,tipo:"corporal",frac:0.45,bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.9,b0:0,db:-3,g:-90,off:0}],
  nota:"Isometria: torque alto o tempo todo e trabalho quase zero, porque não há giro. A nota do boletim despenca por construção."},
 {id:"abdominal-declinado",nome:"Abdominal no banco declinado",grupo:"Abdômen",carga:0,tipo:"corporal",frac:0.32,bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.5,b0:-20,db:-40,g:-90,off:0}],
  nota:"A declinação estende a parte alongada da amplitude e aumenta o pico."},
 {id:"lenhador",nome:"Rotação de tronco na polia",grupo:"Abdômen",carga:20,tipo:"externa",bi:false,
  juntas:[{j:"Tronco",seg:"tronco",f:0.55,b0:150,db:-90,g:180,off:0}],
  nota:"Único da lista que carrega rotação: o braço de momento é a distância das mãos ao eixo do tronco."},

 // ANTEBRAÇO
 {id:"extensao-punho",nome:"Extensão de punho",grupo:"Antebraço",carga:10,tipo:"externa",bi:false,
  juntas:[{j:"Punho",seg:"fixo",f:0.04,b0:-30,db:60,g:-90,off:0}],
  nota:"A alavanca mais curta da biblioteca: pouquíssimo torque para cada quilo."},
 {id:"rosca-punho-invertida",nome:"Rosca de punho por trás do corpo",grupo:"Antebraço",carga:25,tipo:"externa",bi:false,
  juntas:[{j:"Punho",seg:"fixo",f:0.045,b0:-35,db:65,g:-90,off:0}],
  nota:"Barra às costas: mesma alavanca curta, com mais amplitude de punho."},

 // TRAPÉZIO
 {id:"encolhimento-barra",nome:"Encolhimento com barra",grupo:"Trapézio",carga:90,tipo:"externa",bi:true,
  juntas:[{j:"Escápula",seg:"fixo",f:0.02,b0:-45,db:38,g:-90,off:0.05}],
  nota:"Carga alta sobre uma alavanca minúscula — por isso o encolhimento aceita tanto peso."},
 {id:"encolhimento-polia",nome:"Encolhimento na polia baixa",grupo:"Trapézio",carga:60,tipo:"externa",bi:false,
  juntas:[{j:"Escápula",seg:"fixo",f:0.02,b0:-45,db:40,g:-90,off:0.055}],
  nota:"O cabo mantém tensão contínua onde o halter alivia na descida."}

];
